### ISSUE TITLE
快速点击切换报错

### ISSUE THREAD

**Issue by fuxianwen** [angcyo/RecyclerLayoutManager#1]
FATAL EXCEPTION: main Process: com.angcyo.recyclerlayoutmanager, PID: 24599 java.lang.NullPointerException: Attempt to read from field 'android.view.View android.support.v7.widget.RecyclerView$ViewHolder.itemView' on a null object reference
at
 com.angcyo.recyclerlayoutmanager.RenRenCallback.animTo(RenRenCallback.java:139)
                                                                                      at com.angcyo.recyclerlayoutmanager.RenRenCallback.toRight(RenRenCallback.java:133)
                                                                                      at com.angcyo.recyclerlayoutmanager.Main2Activity$4.onClick(Main2Activity.java:87)
                                                                                      at
 android.view.View.performClick(View.java:5609)
                                                                                      at android.view.View$PerformClick.run(View.java:22259)
                                                                                      at android.os.Handler.handleCallback(Handler.java:751)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                      at
 android.os.Looper.loop(Looper.java:154)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                                      at
 java.lang.reflect.Method.invoke(Native Method)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by angcyo** [comment]
已修复.
